"""Reports & Artifacts Hub - View and Download Generated Artifacts"""
import streamlit as st
import sys
import os
from datetime import datetime
import base64

# Add parent directory to path for imports
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))

from ui.nagarro_theme import apply_nagarro_theme
from database import get_db
from auth.auth import DashboardAuth

# Page config
st.set_page_config(
    page_title="Reports & Artifacts | Nagarro Agentic Services",
    page_icon="",
    layout="wide"
)

# CRITICAL: Enforce authentication FIRST
auth = DashboardAuth()
auth.require_auth()

# Apply theme

# Home button
col_home, col_space = st.columns([1, 5])
with col_home:
    if st.button("← Home", key="btn_home", use_container_width=True):
        st.switch_page("app_streamlit.py")
apply_nagarro_theme()

# Get database instance
db = get_db()

# Header
st.markdown('<h1 class="page-title">Reports & Artifacts Hub</h1>', unsafe_allow_html=True)
st.markdown('<p style="color: #B0B0B0; font-size: 1.1rem; margin-bottom: 2rem;">View, preview, and download all generated migration artifacts</p>', unsafe_allow_html=True)

# Quick actions
col1, col2, col3 = st.columns([2, 1, 1])

with col2:
    if st.button(" Refresh", use_container_width=True):
        st.rerun()

with col3:
    if st.button("← Back to Projects", use_container_width=True):
        st.switch_page("pages/2_Projects.py")

st.markdown("---")

# Get all projects for filter
all_projects = db.get_all_projects()

if not all_projects:
    st.warning("️ No projects found. Create a project first to generate artifacts.")
    if st.button(" Create New Project", type="primary"):
        st.switch_page("pages/1_Onboarding.py")
    st.stop()

# ============================================================================
# FILTERS
# ============================================================================

st.markdown('<h2 class="professional-header"> Filters</h2>', unsafe_allow_html=True)

col1, col2, col3, col4 = st.columns(4)

with col1:
    project_filter = st.selectbox(
        "Project",
        ["All Projects"] + [p['name'] for p in all_projects],
        help="Filter artifacts by project"
    )

with col2:
    artifact_types = [
        "All Types",
        "Migration Plan",
        "Wave Plan",
        "Architecture Diagram",
        "Dependency Map",
        "Cost Analysis",
        "Risk Assessment",
        "Compliance Report",
        "Configuration",
        "Documentation"
    ]
    type_filter = st.selectbox(
        "Artifact Type",
        artifact_types,
        help="Filter by artifact type"
    )

with col3:
    agent_filter = st.selectbox(
        "Generated By",
        ["All Agents", "Discovery", "Analysis", "Planning", "Assessment", "Execution"],
        help="Filter by agent that generated the artifact"
    )

with col4:
    sort_by = st.selectbox(
        "Sort By",
        ["Newest First", "Oldest First", "Name (A-Z)", "Type"],
        help="Sort artifacts"
    )

st.markdown("---")

# ============================================================================
# GET AND FILTER ARTIFACTS
# ============================================================================

# Get artifacts based on project filter
if project_filter == "All Projects":
    all_artifacts = []
    for project in all_projects:
        artifacts = db.get_project_artifacts(project['id'])
        for artifact in artifacts:
            artifact['project_name'] = project['name']
            artifact['project_id'] = project['id']
        all_artifacts.extend(artifacts)
else:
    selected_project = next((p for p in all_projects if p['name'] == project_filter), None)
    if selected_project:
        all_artifacts = db.get_project_artifacts(selected_project['id'])
        for artifact in all_artifacts:
            artifact['project_name'] = selected_project['name']
            artifact['project_id'] = selected_project['id']
    else:
        all_artifacts = []

# Apply type filter
if type_filter != "All Types":
    all_artifacts = [a for a in all_artifacts if a.get('artifact_type', '').lower() == type_filter.lower().replace(' ', '_')]

# Apply agent filter
if agent_filter != "All Agents":
    all_artifacts = [a for a in all_artifacts if agent_filter.lower() in a.get('agent_name', '').lower()]

# Apply sorting
if sort_by == "Newest First":
    all_artifacts = sorted(all_artifacts, key=lambda x: x.get('created_at', ''), reverse=True)
elif sort_by == "Oldest First":
    all_artifacts = sorted(all_artifacts, key=lambda x: x.get('created_at', ''))
elif sort_by == "Name (A-Z)":
    all_artifacts = sorted(all_artifacts, key=lambda x: x.get('title', ''))
elif sort_by == "Type":
    all_artifacts = sorted(all_artifacts, key=lambda x: x.get('artifact_type', ''))

# ============================================================================
# DISPLAY ARTIFACTS
# ============================================================================

st.markdown(f'<h2 class="professional-header"> Artifacts ({len(all_artifacts)})</h2>', unsafe_allow_html=True)

if not all_artifacts:
    st.info("ℹ No artifacts found matching your filters. Execute agents to generate artifacts.")
    
    st.markdown("###  How to Generate Artifacts:")
    st.markdown("""
    1. Go to ** Projects** and select a project
    2. Click **️ Execute** to run agents
    3. Agents will generate various artifacts (plans, diagrams, reports)
    4. Return here to view and download the generated artifacts
    """)
else:
    # Summary stats
    col1, col2, col3, col4 = st.columns(4)
    
    with col1:
        st.metric("Total Artifacts", len(all_artifacts))
    
    with col2:
        unique_projects = len(set(a.get('project_id') for a in all_artifacts))
        st.metric("Projects", unique_projects)
    
    with col3:
        unique_types = len(set(a.get('artifact_type') for a in all_artifacts))
        st.metric("Types", unique_types)
    
    with col4:
        total_size = sum(a.get('file_size', 0) for a in all_artifacts)
        size_mb = total_size / (1024 * 1024) if total_size > 0 else 0
        st.metric("Total Size", f"{size_mb:.2f} MB" if size_mb > 0 else "N/A")
    
    st.markdown("---")
    
    # Display artifacts in expandable cards
    for idx, artifact in enumerate(all_artifacts):
        # Artifact type icon
        type_icons = {
            'migration_plan': '',
            'wave_plan': '',
            'architecture_diagram': '️',
            'dependency_map': '',
            'cost_analysis': '',
            'risk_assessment': '️',
            'compliance_report': '',
            'configuration': '️',
            'documentation': '📖'
        }
        
        artifact_type = artifact.get('artifact_type', 'unknown')
        icon = type_icons.get(artifact_type, '')
        
        # Format date
        created_at = artifact.get('created_at', 'N/A')
        if isinstance(created_at, str) and len(created_at) >= 10:
            date_str = created_at[:10]
        else:
            date_str = 'N/A'
        
        # Agent name
        agent_name = artifact.get('agent_name', 'Unknown').replace('_', ' ').title()
        
        with st.expander(f"{icon} {artifact.get('title', 'Untitled')} - {date_str}", expanded=False):
            col1, col2 = st.columns([2, 1])
            
            with col1:
                st.markdown(f"**Description:** {artifact.get('description', 'No description')}")
                st.markdown(f"**Project:** {artifact.get('project_name', 'Unknown')}")
                st.markdown(f"**Generated By:** {agent_name}")
                st.markdown(f"**Type:** {artifact_type.replace('_', ' ').title()}")
                
                if artifact.get('file_path'):
                    st.markdown(f"**File Path:** `{artifact['file_path']}`")
                
                if artifact.get('file_size'):
                    size_kb = artifact['file_size'] / 1024
                    st.markdown(f"**Size:** {size_kb:.2f} KB")
            
            with col2:
                st.markdown(f"**Created:** {created_at}")
                
                # Metadata
                metadata = artifact.get('metadata', {})
                if metadata and isinstance(metadata, dict):
                    st.markdown("**Metadata:**")
                    for key, value in metadata.items():
                        st.markdown(f"- {key}: {value}")
            
            st.markdown("---")
            
            # Preview content if available
            content = artifact.get('content')
            if content:
                st.markdown("### 👁 Preview")
                
                # Determine content type
                if artifact_type in ['migration_plan', 'wave_plan', 'documentation']:
                    # Display as formatted text
                    st.text_area(
                        "Content Preview",
                        content[:2000] + ("..." if len(content) > 2000 else ""),
                        height=300,
                        disabled=True,
                        label_visibility="collapsed"
                    )
                else:
                    # Display as code
                    st.code(
                        content[:2000] + ("..." if len(content) > 2000 else ""),
                        language="text"
                    )
                
                if len(content) > 2000:
                    st.info("ℹ Showing first 2000 characters. Download full artifact below.")
            else:
                st.info("ℹ No content preview available. Artifact may be stored externally.")
            
            # Action buttons
            col1, col2, col3 = st.columns(3)
            
            with col1:
                if content:
                    # Download button
                    download_filename = f"{artifact.get('title', 'artifact')}_{date_str}.txt"
                    st.download_button(
                        label="📥 Download",
                        data=content,
                        file_name=download_filename,
                        mime="text/plain",
                        use_container_width=True
                    )
                else:
                    st.button("📥 Download", disabled=True, use_container_width=True, 
                             help="Content not available in database")
            
            with col2:
                if st.button(" View Project", key=f"view_project_{idx}", use_container_width=True):
                    # Set current project and navigate
                    project = next((p for p in all_projects if p['id'] == artifact['project_id']), None)
                    if project:
                        st.session_state.current_project = project
                        st.switch_page("pages/2_Projects.py")
            
            with col3:
                if st.button("🗑 Delete", key=f"delete_{idx}", use_container_width=True, type="secondary"):
                    st.warning("Delete functionality coming soon!")

# ============================================================================
# BULK ACTIONS
# ============================================================================

if all_artifacts:
    st.markdown("---")
    st.markdown('<h2 class="professional-header">🔧 Bulk Actions</h2>', unsafe_allow_html=True)
    
    col1, col2, col3 = st.columns(3)
    
    with col1:
        if st.button(" Export All (Coming Soon)", use_container_width=True, disabled=True):
            st.info("Bulk export feature coming soon!")
    
    with col2:
        if st.button(" Generate Report (Coming Soon)", use_container_width=True, disabled=True):
            st.info("Artifact summary report coming soon!")
    
    with col3:
        if st.button(" Sync to S3 (Coming Soon)", use_container_width=True, disabled=True):
            st.info("S3 sync feature coming soon!")

# Footer
st.markdown("---")
st.markdown("""
<div style="text-align: center; padding: 2rem; background: #1A1F3A; border-radius: 12px;">
    <h3 style="color: #60c8b1; margin: 0;"> Reports & Artifacts Hub</h3>
    <p style="color: #B0B0B0;">All your migration artifacts in one place</p>
</div>
""", unsafe_allow_html=True)
