#!/usr/bin/env python3
"""Generate demo artifacts"""

from datetime import datetime
import os

def generate_wave_plan_artifact():
    """Generate Wave Plan"""
    from demo.demo_data import DEMO_SCENARIO, WAVE_PLAN
    
    markdown = f"""# Migration Wave Plan
## {DEMO_SCENARIO['company']} - Cloud Migration Strategy

**Generated by Nagarro Agentic Services**  
**Date:** {datetime.now().strftime("%B %d, %Y")}  
**Target Cloud:** {DEMO_SCENARIO['target']}  
**Budget:** {DEMO_SCENARIO['budget']}

---

## Executive Summary

This migration plan sequences {DEMO_SCENARIO['current_environment']['applications']} applications across {WAVE_PLAN['total_waves']} waves over {WAVE_PLAN['timeline']}.

### Key Metrics
- **Applications:** {DEMO_SCENARIO['current_environment']['applications']}
- **Servers:** {DEMO_SCENARIO['current_environment']['servers']}
- **Total Waves:** {WAVE_PLAN['total_waves']}
- **Duration:** {WAVE_PLAN['timeline']}

---

## Migration Waves

"""
    
    for wave in WAVE_PLAN['waves']:
        markdown += f"""### Wave {wave['wave']}: {wave['name']}

- **Duration:** {wave['duration']}
- **Risk Level:** {wave['risk']}
- **Servers:** {wave['servers']}
- **Applications:** {', '.join(wave['apps'])}

**Success Criteria:**
✓ Zero data loss  
✓ <5 min downtime  
✓ Performance maintained  
✓ All integrations validated

---

"""
    
    markdown += """## Risk Mitigation

- Pilot wave validates approach
- Progressive complexity
- 24/7 support for critical systems
- Automated rollback

---

**Powered by Nagarro Agentic Services**  
**Confidence Score:** 92%
"""
    
    os.makedirs('demo/artifacts', exist_ok=True)
    filename = f'demo/artifacts/Wave_Plan.md'
    
    with open(filename, 'w') as f:
        f.write(markdown)
    
    return filename, markdown

def generate_strategy_document():
    """Generate Strategy"""
    from demo.demo_data import DEMO_SCENARIO, ASSESSMENT_RESULTS
    
    markdown = f"""# Cloud Migration Strategy
## {DEMO_SCENARIO['company']}

**Prepared by Nagarro**  
**Date:** {datetime.now().strftime("%B %d, %Y")}

---

## Executive Summary

Strategy for migrating {DEMO_SCENARIO['current_environment']['applications']} applications to {DEMO_SCENARIO['target']}.

### Objectives
1. Modernize Infrastructure
2. Improve Agility
3. Reduce Costs (40% by Year 3)
4. Enhance Security
5. Enable Innovation

---

## Current State

- **Servers:** {DEMO_SCENARIO['current_environment']['servers']}
- **Applications:** {DEMO_SCENARIO['current_environment']['applications']}
- **Readiness Score:** {ASSESSMENT_RESULTS['cloud_readiness_score']}/100

---

## Strategy (6Rs)

| Strategy | % | Approach |
|----------|---|----------|
| Rehost | {ASSESSMENT_RESULTS['migration_strategies']['rehost']}% | Lift-and-shift |
| Replatform | {ASSESSMENT_RESULTS['migration_strategies']['replatform']}% | Optimize |
| Refactor | {ASSESSMENT_RESULTS['migration_strategies']['refactor']}% | Rebuild |
| Retire | {ASSESSMENT_RESULTS['migration_strategies']['retire']}% | Decommission |

---

## Financial Analysis

**Investment:**
- Migration: {ASSESSMENT_RESULTS['cost_projection']['migration_cost']}
- Year 1 Cloud: {ASSESSMENT_RESULTS['cost_projection']['year_1_cloud_cost']}

**ROI:**
- Year 3 Savings: {ASSESSMENT_RESULTS['cost_projection']['year_3_savings']}
- Payback: 18 months

---

**Powered by Nagarro Agentic Services**  
**Confidence:** 92%
"""
    
    os.makedirs('demo/artifacts', exist_ok=True)
    filename = f'demo/artifacts/Migration_Strategy.md'
    
    with open(filename, 'w') as f:
        f.write(markdown)
    
    return filename, markdown
